# Generated by Django 6.1.2 on 2026-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_company_alter_category_name_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-delete: archived products are hidden but history is preserved'),
        ),
    ]
