# Generated by Django 6.1.2 on 2026-10-08 01:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('USD', 'US Dollar ($)'), ('KHR', 'Khmer Riel (៛)')], default='USD', max_length=3)),
                ('usd_to_khr_rate', models.DecimalField(decimal_places=2, default=Decimal('4000.00'), help_text='Number of Khmer Riel for 1 US Dollar.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'global setting',
                'verbose_name_plural': 'global settings',
            },
        ),
    ]
